### PR TITLE
feat: badge and button

### PR DESCRIPTION
**Pull request by deekshithmd**
badge and button

### CODE REVIEW

**Review by PuneetP16 — APPROVED** [review]
Good consistency in colours and class name, Good to Merge.

**Comment by PuneetP16** [comment]
image

The text inside the button is not easily readable.

**Comment by deekshithmd** [comment]
> image
> 
> The text inside the button is not easily readable.

Ok, I will work on this

**Review by anshulraheja — APPROVED** [review]
Well written code. Ready to merge!

**Comment by deekshithmd** [comment]
> Well written code. Ready to merge!

Thank you for the review...

**Pull request merged**
